// jobs — small CLI that publishes events to Kafka. This is the first
// "producer" in the system. It does no DB work; the Store consumer
// listens on the same topics and is responsible for persistence.
//
// Subcommands map 1:1 to event topics:
//
//   add               → job.submitted
//   status            → job.status.changed
//   note add          → job.note.added
//   interview schedule → job.interview.recorded (schedule shape)
//   interview update   → job.interview.recorded (partial update; same topic)
//
// Jobs are identified by `job_id`, a UUID generated by `add` and printed
// to stdout. Follow-up commands (`status`, `note add`, `interview …`)
// take `--job-id` explicitly; the CLI keeps no state and doesn't talk to
// Postgres. URL is descriptive metadata on the job, not its identity —
// postings rename and redirect, the job_id doesn't.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/twmb/franz-go/pkg/kadm"
	"github.com/twmb/franz-go/pkg/kerr"
	"github.com/twmb/franz-go/pkg/kgo"

	"job-tracker/internal/events"
	"job-tracker/internal/jobclient"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	// ensure-topics is admin-only and doesn't go through Publisher.
	if os.Args[1] == "ensure-topics" {
		cmdEnsureTopics()
		return
	}
	switch os.Args[1] {
	case "-h", "--help", "help":
		usage()
		return
	}

	// One Publisher per process, reused across every subcommand. Replaces
	// the old per-call kgo.NewClient pattern.
	pub, err := jobclient.NewPublisher(brokers())
	if err != nil {
		log.Fatalf("publisher: %v", err)
	}
	defer func() {
		if err := pub.Close(); err != nil {
			log.Printf("publisher close: %v", err)
		}
	}()

	switch os.Args[1] {
	case "add":
		cmdAdd(pub, os.Args[2:])
	case "status":
		cmdStatus(pub, os.Args[2:])
	case "note":
		cmdNote(pub, os.Args[2:])
	case "interview":
		cmdInterview(pub, os.Args[2:])
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", os.Args[1])
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage:")
	fmt.Fprintln(os.Stderr, "  jobs ensure-topics")
	fmt.Fprintln(os.Stderr, "  jobs add --url <u> --title <t> --company <c> [metadata flags…]")
	fmt.Fprintln(os.Stderr, "  jobs status <job-id> <new-status>")
	fmt.Fprintln(os.Stderr, "  jobs note add --job-id <id> --body <text>")
	fmt.Fprintln(os.Stderr, "  jobs interview schedule --job-id <id> --round <r> --scheduled-at <ts> [--interviewer <n> …] [--notes <text>]")
	fmt.Fprintln(os.Stderr, "  jobs interview update --interview-id <id> --job-id <id> [--completed-at <ts>] [--outcome <o>] [--interviewer <n> …] [--notes <text>]")
}

// brokers reads KAFKA_BOOTSTRAP (comma-separated) or defaults to the
// host-side listener exposed by compose.yml.
func brokers() []string {
	b := os.Getenv("KAFKA_BOOTSTRAP")
	if b == "" {
		b = "localhost:9092"
	}
	return strings.Split(b, ",")
}

// cmdEnsureTopics creates the topics if they don't already exist. Run
// this once after starting the cluster. Kafka *can* auto-create topics
// on first publish, but explicit creation lets us set partition and
// replication factor up front.
func cmdEnsureTopics() {
	cl, err := kgo.NewClient(kgo.SeedBrokers(brokers()...))
	if err != nil {
		log.Fatalf("kafka client: %v", err)
	}
	defer cl.Close()

	adm := kadm.NewClient(cl)
	topics := []string{
		events.TopicJobSubmitted,
		events.TopicJobStatusChanged,
		events.TopicJobReminder,
		events.TopicJobNoteAdded,
		events.TopicJobInterviewRecorded,
	}

	// 1 partition, 1 replica — fine for a single-broker dev cluster.
	// Increase partitions later if you want parallel consumers in the
	// same consumer group.
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	resp, err := adm.CreateTopics(ctx, 1, 1, nil, topics...)
	if err != nil {
		log.Fatalf("create topics: %v", err)
	}
	for _, r := range resp.Sorted() {
		switch {
		case r.Err == nil:
			fmt.Printf("created: %s\n", r.Topic)
		case errors.Is(r.Err, kerr.TopicAlreadyExists):
			fmt.Printf("exists:  %s\n", r.Topic)
		default:
			fmt.Printf("error:   %s — %v\n", r.Topic, r.Err)
		}
	}
}

func cmdAdd(pub *jobclient.Publisher, args []string) {
	fs := flag.NewFlagSet("add", flag.ExitOnError)

	url := fs.String("url", "", "job posting URL (required)")
	title := fs.String("title", "", "job title (required)")
	company := fs.String("company", "", "company name (required)")
	status := fs.String("status", string(events.StatusSaved), "initial status")

	workMode := fs.String("work-mode", "", "onsite|hybrid|remote")
	location := fs.String("location", "", "city/region")
	seniority := fs.String("seniority", "", "intern|junior|mid|senior|staff|principal")
	source := fs.String("source", "", "linkedin|indeed|referral|company_site|recruiter|other")
	var techTags, customTags stringSlice
	fs.Var(&techTags, "tech-tag", "tech tag (repeatable)")
	fs.Var(&customTags, "custom-tag", "custom tag (repeatable)")
	descFile := fs.String("description-file", "", "path to file containing job description")
	deadline := fs.String("deadline", "", "application deadline (RFC3339 or YYYY-MM-DD)")

	compMin := fs.Float64("comp-min", 0, "minimum compensation (numeric)")
	compMax := fs.Float64("comp-max", 0, "maximum compensation (numeric)")
	compCurrency := fs.String("comp-currency", "", "compensation currency (e.g. USD)")
	compEquity := fs.String("comp-equity", "", "equity description, free-form")
	compBonus := fs.String("comp-bonus", "", "bonus description, free-form")

	resume := fs.String("resume", "", "resume version label")
	coverLetter := fs.String("cover-letter", "", "cover letter version label")
	referral := fs.String("referral", "", "referral name")
	recruiterName := fs.String("recruiter-name", "", "recruiter name")
	recruiterEmail := fs.String("recruiter-email", "", "recruiter email")
	recruiterPhone := fs.String("recruiter-phone", "", "recruiter phone")

	priority := fs.Int("priority", 0, "1 (low) to 5 (high); 0 = unset")

	_ = fs.Parse(args)

	if *url == "" || *title == "" || *company == "" {
		fs.Usage()
		os.Exit(2)
	}

	description := ""
	if *descFile != "" {
		b, err := os.ReadFile(*descFile)
		if err != nil {
			log.Fatalf("read description file: %v", err)
		}
		description = string(b)
	}

	var deadlinePtr *time.Time
	if *deadline != "" {
		t, err := parseTime(*deadline)
		if err != nil {
			log.Fatalf("--deadline: %v", err)
		}
		deadlinePtr = &t
	}

	jobID := uuid.NewString()
	ev := events.JobSubmitted{
		EventID:     uuid.NewString(),
		JobID:       jobID,
		URL:         *url,
		Title:       *title,
		Company:     *company,
		Status:      events.JobStatus(*status),
		SubmittedAt: time.Now().UTC(),

		WorkMode:    events.WorkMode(*workMode),
		Location:    *location,
		Seniority:   events.Seniority(*seniority),
		Source:      events.Source(*source),
		TechTags:    []string(techTags),
		Description: description,
		Deadline:    deadlinePtr,

		CompMin:      floatPtrIfSet(fs, "comp-min", *compMin),
		CompMax:      floatPtrIfSet(fs, "comp-max", *compMax),
		CompCurrency: *compCurrency,
		CompEquity:   *compEquity,
		CompBonus:    *compBonus,

		ResumeVersion:      *resume,
		CoverLetterVersion: *coverLetter,
		Referral:           *referral,
		RecruiterName:      *recruiterName,
		RecruiterEmail:     *recruiterEmail,
		RecruiterPhone:     *recruiterPhone,

		Priority:   intPtrIfSet(fs, "priority", *priority),
		CustomTags: []string(customTags),
	}
	ctx, cancel := publishCtx()
	defer cancel()
	if err := pub.Submit(ctx, ev); err != nil {
		log.Fatalf("publish: %v", err)
	}
	fmt.Printf("published: %s @ %s (%s)\n", ev.Title, ev.Company, ev.Status)
	fmt.Printf("job_id: %s\n", ev.JobID)
	fmt.Println("(save this id — `status`, `note add`, and `interview …` need it.)")
}

func cmdStatus(pub *jobclient.Publisher, args []string) {
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: jobs status <job-id> <new-status>")
		os.Exit(2)
	}
	ev := events.JobStatusChanged{
		EventID:   uuid.NewString(),
		JobID:     args[0],
		Status:    events.JobStatus(args[1]),
		ChangedAt: time.Now().UTC(),
	}
	ctx, cancel := publishCtx()
	defer cancel()
	if err := pub.ChangeStatus(ctx, ev); err != nil {
		log.Fatalf("publish: %v", err)
	}
	fmt.Printf("status changed: %s → %s\n", ev.JobID, ev.Status)
}

func cmdNote(pub *jobclient.Publisher, args []string) {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "usage: jobs note add --job-id <id> --body <text>")
		os.Exit(2)
	}
	switch args[0] {
	case "add":
		cmdNoteAdd(pub, args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown note subcommand: %s\n", args[0])
		os.Exit(2)
	}
}

func cmdNoteAdd(pub *jobclient.Publisher, args []string) {
	fs := flag.NewFlagSet("note add", flag.ExitOnError)
	jobID := fs.String("job-id", "", "job id from `add` (required)")
	body := fs.String("body", "", "note body (required)")
	_ = fs.Parse(args)

	if *jobID == "" || *body == "" {
		fs.Usage()
		os.Exit(2)
	}

	ev := events.JobNoteAdded{
		EventID:   uuid.NewString(),
		JobID:     *jobID,
		Body:      *body,
		CreatedAt: time.Now().UTC(),
	}
	ctx, cancel := publishCtx()
	defer cancel()
	if err := pub.AddNote(ctx, ev); err != nil {
		log.Fatalf("publish: %v", err)
	}
	fmt.Printf("note added: %s\n", ev.JobID)
}

func cmdInterview(pub *jobclient.Publisher, args []string) {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr, "usage: jobs interview schedule|update …")
		os.Exit(2)
	}
	switch args[0] {
	case "schedule":
		cmdInterviewSchedule(pub, args[1:])
	case "update":
		cmdInterviewUpdate(pub, args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown interview subcommand: %s\n", args[0])
		os.Exit(2)
	}
}

func cmdInterviewSchedule(pub *jobclient.Publisher, args []string) {
	fs := flag.NewFlagSet("interview schedule", flag.ExitOnError)
	jobID := fs.String("job-id", "", "job id from `add` (required)")
	round := fs.String("round", "", "phone_screen|technical|behavioral|system_design|onsite|final|other (required)")
	scheduledAt := fs.String("scheduled-at", "", "RFC3339 timestamp or YYYY-MM-DD (required)")
	var interviewers stringSlice
	fs.Var(&interviewers, "interviewer", "interviewer name (repeatable)")
	notes := fs.String("notes", "", "free-text notes")
	_ = fs.Parse(args)

	if *jobID == "" || *round == "" || *scheduledAt == "" {
		fs.Usage()
		os.Exit(2)
	}

	ts, err := parseTime(*scheduledAt)
	if err != nil {
		log.Fatalf("--scheduled-at: %v", err)
	}

	ev := events.JobInterviewRecorded{
		EventID:      uuid.NewString(),
		InterviewID:  uuid.NewString(),
		JobID:        *jobID,
		Round:        events.InterviewRound(*round),
		ScheduledAt:  &ts,
		Interviewers: []string(interviewers),
		Notes:        *notes,
		RecordedAt:   time.Now().UTC(),
	}
	ctx, cancel := publishCtx()
	defer cancel()
	if err := pub.RecordInterview(ctx, ev); err != nil {
		log.Fatalf("publish: %v", err)
	}
	fmt.Printf("interview scheduled: %s (round=%s)\n", ev.JobID, ev.Round)
	fmt.Printf("interview_id: %s\n", ev.InterviewID)
	fmt.Println("(save this id — `interview update` needs it.)")
}

func cmdInterviewUpdate(pub *jobclient.Publisher, args []string) {
	fs := flag.NewFlagSet("interview update", flag.ExitOnError)
	interviewID := fs.String("interview-id", "", "interview id from `interview schedule` (required)")
	jobID := fs.String("job-id", "", "job id from `add` (required; partition key)")
	completedAt := fs.String("completed-at", "", "RFC3339 timestamp or YYYY-MM-DD")
	outcome := fs.String("outcome", "", "passed|failed|no_show|pending|withdrawn")
	var interviewers stringSlice
	fs.Var(&interviewers, "interviewer", "interviewer name (repeatable; replaces list when provided)")
	notes := fs.String("notes", "", "free-text notes")
	round := fs.String("round", "", "override round (rarely needed)")
	scheduledAt := fs.String("scheduled-at", "", "override scheduled timestamp (rarely needed)")
	_ = fs.Parse(args)

	if *interviewID == "" || *jobID == "" {
		fs.Usage()
		os.Exit(2)
	}

	ev := events.JobInterviewRecorded{
		EventID:     uuid.NewString(),
		InterviewID: *interviewID,
		JobID:       *jobID,
		Round:       events.InterviewRound(*round),
		Outcome:     events.InterviewOutcome(*outcome),
		Notes:       *notes,
		RecordedAt:  time.Now().UTC(),
	}
	if *scheduledAt != "" {
		ts, err := parseTime(*scheduledAt)
		if err != nil {
			log.Fatalf("--scheduled-at: %v", err)
		}
		ev.ScheduledAt = &ts
	}
	if *completedAt != "" {
		ts, err := parseTime(*completedAt)
		if err != nil {
			log.Fatalf("--completed-at: %v", err)
		}
		ev.CompletedAt = &ts
	}
	// nil slice → leave existing list alone (store COALESCEs on the raw
	// parameter). Non-nil (even empty) → replace.
	if len(interviewers) > 0 {
		ev.Interviewers = []string(interviewers)
	}
	ctx, cancel := publishCtx()
	defer cancel()
	if err := pub.RecordInterview(ctx, ev); err != nil {
		log.Fatalf("publish: %v", err)
	}
	fmt.Printf("interview updated: %s\n", ev.InterviewID)
}

// publishCtx is the per-call timeout for a single ProduceSync — the
// Publisher itself is process-lived, so this only bounds an individual
// publish round trip.
func publishCtx() (context.Context, context.CancelFunc) {
	return context.WithTimeout(context.Background(), 10*time.Second)
}

// stringSlice collects repeated --flag values into a slice.
type stringSlice []string

func (s *stringSlice) String() string     { return strings.Join(*s, ",") }
func (s *stringSlice) Set(v string) error { *s = append(*s, v); return nil }

// parseTime accepts RFC3339 first, then YYYY-MM-DD (treated as UTC
// midnight). Keeps the CLI ergonomic for both deadlines (date) and
// interview slots (full timestamp).
func parseTime(s string) (time.Time, error) {
	if t, err := time.Parse(time.RFC3339, s); err == nil {
		return t.UTC(), nil
	}
	if t, err := time.Parse("2006-01-02", s); err == nil {
		return t.UTC(), nil
	}
	return time.Time{}, fmt.Errorf("expected RFC3339 or YYYY-MM-DD, got %q", s)
}

// floatPtrIfSet returns &v if the flag was explicitly passed (even with
// value 0), nil otherwise. Lets the user submit comp-min=0 distinctly
// from "not specified".
func floatPtrIfSet(fs *flag.FlagSet, name string, v float64) *float64 {
	if !flagWasSet(fs, name) {
		return nil
	}
	return &v
}

func intPtrIfSet(fs *flag.FlagSet, name string, v int) *int {
	if !flagWasSet(fs, name) {
		return nil
	}
	return &v
}

func flagWasSet(fs *flag.FlagSet, name string) bool {
	found := false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == name {
			found = true
		}
	})
	return found
}
